// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: apex.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ApexCoordinator_SubmitPlan_FullMethodName = "/apex.v1.ApexCoordinator/SubmitPlan"
)

// ApexCoordinatorClient is the client API for ApexCoordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for distributed coordination
type ApexCoordinatorClient interface {
	// Receives an optimized physical plan and distributes it across the cluster
	SubmitPlan(ctx context.Context, in *SubmitPlanRequest, opts ...grpc.CallOption) (*SubmitPlanResponse, error)
}

type apexCoordinatorClient struct {
	cc grpc.ClientConnInterface
}

func NewApexCoordinatorClient(cc grpc.ClientConnInterface) ApexCoordinatorClient {
	return &apexCoordinatorClient{cc}
}

func (c *apexCoordinatorClient) SubmitPlan(ctx context.Context, in *SubmitPlanRequest, opts ...grpc.CallOption) (*SubmitPlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubmitPlanResponse)
	err := c.cc.Invoke(ctx, ApexCoordinator_SubmitPlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApexCoordinatorServer is the server API for ApexCoordinator service.
// All implementations must embed UnimplementedApexCoordinatorServer
// for forward compatibility.
//
// Service for distributed coordination
type ApexCoordinatorServer interface {
	// Receives an optimized physical plan and distributes it across the cluster
	SubmitPlan(context.Context, *SubmitPlanRequest) (*SubmitPlanResponse, error)
	mustEmbedUnimplementedApexCoordinatorServer()
}

// UnimplementedApexCoordinatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApexCoordinatorServer struct{}

func (UnimplementedApexCoordinatorServer) SubmitPlan(context.Context, *SubmitPlanRequest) (*SubmitPlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitPlan not implemented")
}
func (UnimplementedApexCoordinatorServer) mustEmbedUnimplementedApexCoordinatorServer() {}
func (UnimplementedApexCoordinatorServer) testEmbeddedByValue()                         {}

// UnsafeApexCoordinatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApexCoordinatorServer will
// result in compilation errors.
type UnsafeApexCoordinatorServer interface {
	mustEmbedUnimplementedApexCoordinatorServer()
}

func RegisterApexCoordinatorServer(s grpc.ServiceRegistrar, srv ApexCoordinatorServer) {
	// If the following call panics, it indicates UnimplementedApexCoordinatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApexCoordinator_ServiceDesc, srv)
}

func _ApexCoordinator_SubmitPlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitPlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApexCoordinatorServer).SubmitPlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApexCoordinator_SubmitPlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApexCoordinatorServer).SubmitPlan(ctx, req.(*SubmitPlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApexCoordinator_ServiceDesc is the grpc.ServiceDesc for ApexCoordinator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApexCoordinator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apex.v1.ApexCoordinator",
	HandlerType: (*ApexCoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitPlan",
			Handler:    _ApexCoordinator_SubmitPlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apex.proto",
}

const (
	ApexExecution_ExecutePlan_FullMethodName = "/apex.v1.ApexExecution/ExecutePlan"
)

// ApexExecutionClient is the client API for ApexExecution service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for local node execution (Rust JIT)
type ApexExecutionClient interface {
	// Executes a physical plan slice on the local node
	ExecutePlan(ctx context.Context, in *ExecutePlanRequest, opts ...grpc.CallOption) (*ExecutePlanResponse, error)
}

type apexExecutionClient struct {
	cc grpc.ClientConnInterface
}

func NewApexExecutionClient(cc grpc.ClientConnInterface) ApexExecutionClient {
	return &apexExecutionClient{cc}
}

func (c *apexExecutionClient) ExecutePlan(ctx context.Context, in *ExecutePlanRequest, opts ...grpc.CallOption) (*ExecutePlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutePlanResponse)
	err := c.cc.Invoke(ctx, ApexExecution_ExecutePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApexExecutionServer is the server API for ApexExecution service.
// All implementations must embed UnimplementedApexExecutionServer
// for forward compatibility.
//
// Service for local node execution (Rust JIT)
type ApexExecutionServer interface {
	// Executes a physical plan slice on the local node
	ExecutePlan(context.Context, *ExecutePlanRequest) (*ExecutePlanResponse, error)
	mustEmbedUnimplementedApexExecutionServer()
}

// UnimplementedApexExecutionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApexExecutionServer struct{}

func (UnimplementedApexExecutionServer) ExecutePlan(context.Context, *ExecutePlanRequest) (*ExecutePlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecutePlan not implemented")
}
func (UnimplementedApexExecutionServer) mustEmbedUnimplementedApexExecutionServer() {}
func (UnimplementedApexExecutionServer) testEmbeddedByValue()                       {}

// UnsafeApexExecutionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApexExecutionServer will
// result in compilation errors.
type UnsafeApexExecutionServer interface {
	mustEmbedUnimplementedApexExecutionServer()
}

func RegisterApexExecutionServer(s grpc.ServiceRegistrar, srv ApexExecutionServer) {
	// If the following call panics, it indicates UnimplementedApexExecutionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApexExecution_ServiceDesc, srv)
}

func _ApexExecution_ExecutePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApexExecutionServer).ExecutePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApexExecution_ExecutePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApexExecutionServer).ExecutePlan(ctx, req.(*ExecutePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApexExecution_ServiceDesc is the grpc.ServiceDesc for ApexExecution service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApexExecution_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apex.v1.ApexExecution",
	HandlerType: (*ApexExecutionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecutePlan",
			Handler:    _ApexExecution_ExecutePlan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apex.proto",
}

const (
	ApexOptimizer_Optimize_FullMethodName = "/apex.v1.ApexOptimizer/Optimize"
)

// ApexOptimizerClient is the client API for ApexOptimizer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for Haskell query optimization
type ApexOptimizerClient interface {
	// Receives a logical plan from Go, returns an optimized physical plan
	Optimize(ctx context.Context, in *OptimizePlanRequest, opts ...grpc.CallOption) (*OptimizePlanResponse, error)
}

type apexOptimizerClient struct {
	cc grpc.ClientConnInterface
}

func NewApexOptimizerClient(cc grpc.ClientConnInterface) ApexOptimizerClient {
	return &apexOptimizerClient{cc}
}

func (c *apexOptimizerClient) Optimize(ctx context.Context, in *OptimizePlanRequest, opts ...grpc.CallOption) (*OptimizePlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OptimizePlanResponse)
	err := c.cc.Invoke(ctx, ApexOptimizer_Optimize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApexOptimizerServer is the server API for ApexOptimizer service.
// All implementations must embed UnimplementedApexOptimizerServer
// for forward compatibility.
//
// Service for Haskell query optimization
type ApexOptimizerServer interface {
	// Receives a logical plan from Go, returns an optimized physical plan
	Optimize(context.Context, *OptimizePlanRequest) (*OptimizePlanResponse, error)
	mustEmbedUnimplementedApexOptimizerServer()
}

// UnimplementedApexOptimizerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedApexOptimizerServer struct{}

func (UnimplementedApexOptimizerServer) Optimize(context.Context, *OptimizePlanRequest) (*OptimizePlanResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Optimize not implemented")
}
func (UnimplementedApexOptimizerServer) mustEmbedUnimplementedApexOptimizerServer() {}
func (UnimplementedApexOptimizerServer) testEmbeddedByValue()                       {}

// UnsafeApexOptimizerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApexOptimizerServer will
// result in compilation errors.
type UnsafeApexOptimizerServer interface {
	mustEmbedUnimplementedApexOptimizerServer()
}

func RegisterApexOptimizerServer(s grpc.ServiceRegistrar, srv ApexOptimizerServer) {
	// If the following call panics, it indicates UnimplementedApexOptimizerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ApexOptimizer_ServiceDesc, srv)
}

func _ApexOptimizer_Optimize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimizePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApexOptimizerServer).Optimize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApexOptimizer_Optimize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApexOptimizerServer).Optimize(ctx, req.(*OptimizePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApexOptimizer_ServiceDesc is the grpc.ServiceDesc for ApexOptimizer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApexOptimizer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "apex.v1.ApexOptimizer",
	HandlerType: (*ApexOptimizerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Optimize",
			Handler:    _ApexOptimizer_Optimize_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apex.proto",
}
