// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: apex.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitPlanRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	QueryId          string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	PhysicalPlanJson []byte                 `protobuf:"bytes,2,opt,name=physical_plan_json,json=physicalPlanJson,proto3" json:"physical_plan_json,omitempty"` // Serialize the Haskell AST to JSON
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubmitPlanRequest) Reset() {
	*x = SubmitPlanRequest{}
	mi := &file_apex_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPlanRequest) ProtoMessage() {}

func (x *SubmitPlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apex_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPlanRequest.ProtoReflect.Descriptor instead.
func (*SubmitPlanRequest) Descriptor() ([]byte, []int) {
	return file_apex_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitPlanRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *SubmitPlanRequest) GetPhysicalPlanJson() []byte {
	if x != nil {
		return x.PhysicalPlanJson
	}
	return nil
}

type SubmitPlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitPlanResponse) Reset() {
	*x = SubmitPlanResponse{}
	mi := &file_apex_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitPlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitPlanResponse) ProtoMessage() {}

func (x *SubmitPlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apex_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitPlanResponse.ProtoReflect.Descriptor instead.
func (*SubmitPlanResponse) Descriptor() ([]byte, []int) {
	return file_apex_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitPlanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitPlanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ExecutePlanRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	QueryId          string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	PhysicalPlanJson []byte                 `protobuf:"bytes,2,opt,name=physical_plan_json,json=physicalPlanJson,proto3" json:"physical_plan_json,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecutePlanRequest) Reset() {
	*x = ExecutePlanRequest{}
	mi := &file_apex_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePlanRequest) ProtoMessage() {}

func (x *ExecutePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apex_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePlanRequest.ProtoReflect.Descriptor instead.
func (*ExecutePlanRequest) Descriptor() ([]byte, []int) {
	return file_apex_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutePlanRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *ExecutePlanRequest) GetPhysicalPlanJson() []byte {
	if x != nil {
		return x.PhysicalPlanJson
	}
	return nil
}

type ExecutePlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ResultData    string                 `protobuf:"bytes,2,opt,name=result_data,json=resultData,proto3" json:"result_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePlanResponse) Reset() {
	*x = ExecutePlanResponse{}
	mi := &file_apex_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePlanResponse) ProtoMessage() {}

func (x *ExecutePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apex_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePlanResponse.ProtoReflect.Descriptor instead.
func (*ExecutePlanResponse) Descriptor() ([]byte, []int) {
	return file_apex_proto_rawDescGZIP(), []int{3}
}

func (x *ExecutePlanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecutePlanResponse) GetResultData() string {
	if x != nil {
		return x.ResultData
	}
	return ""
}

// Structured Go AST sent to Haskell
type LogicalPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryType     string                 `protobuf:"bytes,1,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"`
	TableNames    []string               `protobuf:"bytes,2,rep,name=table_names,json=tableNames,proto3" json:"table_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalPlan) Reset() {
	*x = LogicalPlan{}
	mi := &file_apex_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalPlan) ProtoMessage() {}

func (x *LogicalPlan) ProtoReflect() protoreflect.Message {
	mi := &file_apex_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalPlan.ProtoReflect.Descriptor instead.
func (*LogicalPlan) Descriptor() ([]byte, []int) {
	return file_apex_proto_rawDescGZIP(), []int{4}
}

func (x *LogicalPlan) GetQueryType() string {
	if x != nil {
		return x.QueryType
	}
	return ""
}

func (x *LogicalPlan) GetTableNames() []string {
	if x != nil {
		return x.TableNames
	}
	return nil
}

type OptimizePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       string                 `protobuf:"bytes,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	LogicalPlan   *LogicalPlan           `protobuf:"bytes,2,opt,name=logical_plan,json=logicalPlan,proto3" json:"logical_plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizePlanRequest) Reset() {
	*x = OptimizePlanRequest{}
	mi := &file_apex_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizePlanRequest) ProtoMessage() {}

func (x *OptimizePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apex_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizePlanRequest.ProtoReflect.Descriptor instead.
func (*OptimizePlanRequest) Descriptor() ([]byte, []int) {
	return file_apex_proto_rawDescGZIP(), []int{5}
}

func (x *OptimizePlanRequest) GetQueryId() string {
	if x != nil {
		return x.QueryId
	}
	return ""
}

func (x *OptimizePlanRequest) GetLogicalPlan() *LogicalPlan {
	if x != nil {
		return x.LogicalPlan
	}
	return nil
}

type OptimizePlanResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PhysicalPlanJson []byte                 `protobuf:"bytes,2,opt,name=physical_plan_json,json=physicalPlanJson,proto3" json:"physical_plan_json,omitempty"` // Returns the optimized HashJoin JSON!
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OptimizePlanResponse) Reset() {
	*x = OptimizePlanResponse{}
	mi := &file_apex_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizePlanResponse) ProtoMessage() {}

func (x *OptimizePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apex_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizePlanResponse.ProtoReflect.Descriptor instead.
func (*OptimizePlanResponse) Descriptor() ([]byte, []int) {
	return file_apex_proto_rawDescGZIP(), []int{6}
}

func (x *OptimizePlanResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OptimizePlanResponse) GetPhysicalPlanJson() []byte {
	if x != nil {
		return x.PhysicalPlanJson
	}
	return nil
}

var File_apex_proto protoreflect.FileDescriptor

const file_apex_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"apex.proto\x12\aapex.v1\"\\\n" +
	"\x11SubmitPlanRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12,\n" +
	"\x12physical_plan_json\x18\x02 \x01(\fR\x10physicalPlanJson\"H\n" +
	"\x12SubmitPlanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"]\n" +
	"\x12ExecutePlanRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x12,\n" +
	"\x12physical_plan_json\x18\x02 \x01(\fR\x10physicalPlanJson\"P\n" +
	"\x13ExecutePlanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vresult_data\x18\x02 \x01(\tR\n" +
	"resultData\"M\n" +
	"\vLogicalPlan\x12\x1d\n" +
	"\n" +
	"query_type\x18\x01 \x01(\tR\tqueryType\x12\x1f\n" +
	"\vtable_names\x18\x02 \x03(\tR\n" +
	"tableNames\"i\n" +
	"\x13OptimizePlanRequest\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\tR\aqueryId\x127\n" +
	"\flogical_plan\x18\x02 \x01(\v2\x14.apex.v1.LogicalPlanR\vlogicalPlan\"^\n" +
	"\x14OptimizePlanResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12,\n" +
	"\x12physical_plan_json\x18\x02 \x01(\fR\x10physicalPlanJson2X\n" +
	"\x0fApexCoordinator\x12E\n" +
	"\n" +
	"SubmitPlan\x12\x1a.apex.v1.SubmitPlanRequest\x1a\x1b.apex.v1.SubmitPlanResponse2Y\n" +
	"\rApexExecution\x12H\n" +
	"\vExecutePlan\x12\x1b.apex.v1.ExecutePlanRequest\x1a\x1c.apex.v1.ExecutePlanResponse2X\n" +
	"\rApexOptimizer\x12G\n" +
	"\bOptimize\x12\x1c.apex.v1.OptimizePlanRequest\x1a\x1d.apex.v1.OptimizePlanResponseB\x1cZ\x1agithub.com/apex/raft/protob\x06proto3"

var (
	file_apex_proto_rawDescOnce sync.Once
	file_apex_proto_rawDescData []byte
)

func file_apex_proto_rawDescGZIP() []byte {
	file_apex_proto_rawDescOnce.Do(func() {
		file_apex_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apex_proto_rawDesc), len(file_apex_proto_rawDesc)))
	})
	return file_apex_proto_rawDescData
}

var file_apex_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_apex_proto_goTypes = []any{
	(*SubmitPlanRequest)(nil),    // 0: apex.v1.SubmitPlanRequest
	(*SubmitPlanResponse)(nil),   // 1: apex.v1.SubmitPlanResponse
	(*ExecutePlanRequest)(nil),   // 2: apex.v1.ExecutePlanRequest
	(*ExecutePlanResponse)(nil),  // 3: apex.v1.ExecutePlanResponse
	(*LogicalPlan)(nil),          // 4: apex.v1.LogicalPlan
	(*OptimizePlanRequest)(nil),  // 5: apex.v1.OptimizePlanRequest
	(*OptimizePlanResponse)(nil), // 6: apex.v1.OptimizePlanResponse
}
var file_apex_proto_depIdxs = []int32{
	4, // 0: apex.v1.OptimizePlanRequest.logical_plan:type_name -> apex.v1.LogicalPlan
	0, // 1: apex.v1.ApexCoordinator.SubmitPlan:input_type -> apex.v1.SubmitPlanRequest
	2, // 2: apex.v1.ApexExecution.ExecutePlan:input_type -> apex.v1.ExecutePlanRequest
	5, // 3: apex.v1.ApexOptimizer.Optimize:input_type -> apex.v1.OptimizePlanRequest
	1, // 4: apex.v1.ApexCoordinator.SubmitPlan:output_type -> apex.v1.SubmitPlanResponse
	3, // 5: apex.v1.ApexExecution.ExecutePlan:output_type -> apex.v1.ExecutePlanResponse
	6, // 6: apex.v1.ApexOptimizer.Optimize:output_type -> apex.v1.OptimizePlanResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apex_proto_init() }
func file_apex_proto_init() {
	if File_apex_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apex_proto_rawDesc), len(file_apex_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_apex_proto_goTypes,
		DependencyIndexes: file_apex_proto_depIdxs,
		MessageInfos:      file_apex_proto_msgTypes,
	}.Build()
	File_apex_proto = out.File
	file_apex_proto_goTypes = nil
	file_apex_proto_depIdxs = nil
}
